Add missing include
Fix ' concurrency.h:606:10: error: ‘atomic_bool’ in namespace ‘std’ does not name a type; did you mean ‘atomic_load’? ' build error.